### ISSUE TITLE
just passed by your page on hackster

### ISSUE THREAD

**Issue by dojomats** [mjdargen/Teachable-Machine-Object-Detection#3]
https://www.hackster.io/mjdargen/easy-object-detection-with-teachable-machine-python-d4063b#comments

Just wondering if you managed to get bounding boxes from teachable machine's custom model set?
I'm looking to do a pan tilt camera mount with the model from teachable machine, using a raspberry pi

**Comment by mjdargen** [comment]
Sadly, that is beyond the scope of what a Teachable Machine module can do. It is unable to recognize multiple objects within an image (unless you explicitly train classes for when multiple objects are in view). Essentially what it does is look at the entire image and compare it to the classes that you trained it on. The model then makes a determination on which class it most closely aligns with. Since it looks at the entire image and not pieces of the image, it is not possible to do bounding boxes since the bounding box area would be the entire image.

If you are looking to do something that will recognize multiple objects within a single frame with bounding boxes, you may want to investigate training your own module outside of Teachable Machine or using an already existing YOLO model like the one I referenced ([https://www.visiongeek.io/2018/07/yolo-object-detection-opencv-python.html](https://www.visiongeek.io/2018/07/yolo-object-detection-opencv-python.html)). Best of luck!
